src/Organizations/OrgsBundle/Entity/Worker.php
<?php

namespace Organizations\OrgsBundle\Entity;

/**
 * Worker
 */
class Worker
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $lastname;

    /**
     * @var string
     */
    private $firstname;

    /**
     * @var string
     */
    private $middlename;

    /**
     * @var \DateTime
     */
    private $birthday;

    /**
     * @var string
     */
    private $inn;

    /**
     * @var string
     */
    private $snils;

    /**
     * @var \Organizations\OrgsBundle\Entity\Organization
     */
    /**
     * @ORM\ManyToOne(targetEntity="Organization", inversedBy="workers")
     * @ORM\JoinColumn(name="organization_id", referencedColumnName="id")
     */
    private $organization;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     * @return Worker
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     * @return Worker
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set middlename
     *
     * @param string $middlename
     * @return Worker
     */
    public function setMiddlename($middlename)
    {
        $this->middlename = $middlename;

        return $this;
    }

    /**
     * Get middlename
     *
     * @return string 
     */
    public function getMiddlename()
    {
        return $this->middlename;
    }

    /**
     * Set birthday
     *
     * @param \DateTime $birthday
     * @return Worker
     */
    public function setBirthday($birthday)
    {
        $this->birthday = $birthday;

        return $this;
    }

    /**
     * Get birthday
     *
     * @return \DateTime 
     */
    public function getBirthday()
    {
        return $this->birthday;
    }

    /**
     * Set inn
     *
     * @param string $inn
     * @return Worker
     */
    public function setInn($inn)
    {
        $this->inn = $inn;

        return $this;
    }

    /**
     * Get inn
     *
     * @return string 
     */
    public function getInn()
    {
        return $this->inn;
    }

    /**
     * Set snils
     *
     * @param string $snils
     * @return Worker
     */
    public function setSnils($snils)
    {
        $this->snils = $snils;

        return $this;
    }

    /**
     * Get snils
     *
     * @return string 
     */
    public function getSnils()
    {
        return $this->snils;
    }

    /**
     * Set organization
     *
     * @param \Organizations\OrgsBundle\Entity\Organization $organization
     * @return Worker
     */
    public function setOrganization(\Organizations\OrgsBundle\Entity\Organization $organization = null)
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * Get organization
     *
     * @return \Organizations\OrgsBundle\Entity\Organization 
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    public function getFullName()
    {
        return $this->lastname . " " . $this->firstname . " " . $this->middlename;
    }

    public function __toString()
    {
        return "Worker: id - " . $this->id . "; lastname - " . $this->lastname . "; firstname - " . $this->firstname
            . "; middlename - " . $this->middlename . "; birthday - " . $this->birthday . "; inn - " . $this->inn
            . "; snils - " . $this->snils;
    }
}

src/Organizations/OrgsBundle/Form/WorkerForm.php
<?php
/**
 * Created by PhpStorm.
 * User: eugene.kuzob
 * Date: 03.11.2017
 * Time: 10:45
 */

namespace Organizations\OrgsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\FormBuilderInterface;

class WorkerForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
//        $builder->add('title', "text", array("label" => "Наименование", "required" => true));
//        $builder->add('ogrn', "text", array("label" => "ОГРН", "required" => true));
//        $builder->add('oktmo', "text", array("label" => "ОКТМО", "required" => true));
        $builder->add('lastname', "text");
        $builder->add('firstname', "text");
        $builder->add('middlename', "text");
        $builder->add('birthday', BirthdayType::class, array(
                                'empty_value' => array('year' => 'Year', 'month'=>'Month', 'day'=>'Day')));
        $builder->add('inn', "text");
        $builder->add('snils', "text");
    }

    public function getDefaultOptions(array $options)
    {
        return array(
            'data_class' => 'Organizations\OrgsBundle\Entity\Worker',
        );
    }

    public function getName()
    {
        return 'worker';
    }
}

src/Organizations/OrgsBundle/Controller/WorkerController.php
<?php
/**
 * Created by PhpStorm.
 * User: eugene.kuzob
 * Date: 02.11.2017
 * Time: 15:37
 */

namespace Organizations\OrgsBundle\Controller;

use Symfony\Component\HttpFoundation\Request;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use Organizations\OrgsBundle\Entity\Worker;

use Organizations\OrgsBundle\Form\WorkerForm;

class WorkerController extends Controller
{
    private $logger = null;

    private function getLogger()
    {
        if ($this->logger == null)
        {
            $this->logger = $this->get('logger');
        }
        return $this->logger;
    }

    public function workerInfoAction($orgId, $id)
    {
        $this->getLogger()->info("View info about Worker with id - " . $id);

        $em = $this->getDoctrine()->getEntityManager();
        $worker = $em->getRepository('OrgsBundle:Worker')->findOneBy(array('id' => $id));

        return $this->render('OrgsBundle:Worker:worker_info.html.twig', array('worker'=> $worker, "orgId" => $orgId));
    }

    public function workerCreateAction(Request $request, $orgId)
    {
        $this->getLogger()->info("Create form for Worker");

        $worker = new Worker();

        $form = $this->createForm(new WorkerForm(), $worker);

        if( $request->getMethod() == 'POST') {
            $form->submit($request);
            if($form->isValid()) {
                $this->getLogger()->err("Create new Worker is success");

                $em = $this->getDoctrine()->getEntityManager();

                $organization = $em->getRepository('OrgsBundle:Organization') ->findOneBy(array('id' => $orgId));
                $worker->setOrganization($organization);

                $em->persist($worker);
                $em->flush();

                $this->getLogger()->err("Worker created in database with id - " . $worker->getId());

                $this->addFlash(
                    'notice',
                    $this->get('translator')->trans('notice.create.worker.is.done',
                        array('%fullname%' => $worker->getFullName())));

                return $this->redirect($this->generateUrl('worker_info', array('orgId' => $orgId, 'id' => $worker->getId())));
            }
            else {
                $this->getLogger()->err("Form Worker is not correct");
            }
        }

        return $this->render('OrgsBundle:Worker:worker_new.html.twig', array('form' => $form->createView(), 'orgId' => $orgId));
    }

    public function workerEditAction(Request $request, $orgId, $id)
    {
        $this->getLogger()->info("Edit Worker with id - " . $id);

        $em = $this->getDoctrine()->getEntityManager();
        $worker = $em->getRepository('OrgsBundle:Worker') ->findOneBy(array('id' => $id));

        $form = $this->createForm(new WorkerForm(), $worker);

        if( $request->getMethod() == 'POST') {
            $form->submit($request);
            if($form->isValid()) {
                $this->getLogger()->err("Edit Worker with id: " . $id);

                $em = $this->getDoctrine()->getEntityManager();
                $em->persist($worker);
                $em->flush();

                $this->getLogger()->err("Worker edit in database with id - " . $worker->getId());

                $this->addFlash(
                    'notice',
                    $this->get('translator')->trans('notice.editing.worker.successful',
                        array('%fullname%' => $worker->getFullName())));

                return $this->redirect($this->generateUrl('worker_info', array('orgId' => $orgId, 'id' => $worker->getId())));
            }
            else {
                $this->getLogger()->err("Form Worker is not correct");
            }
        }

        return $this->render('OrgsBundle:Worker:worker_edit.html.twig',
                                array('form' => $form->createView(), 'orgId' => $orgId, 'worker' => $worker));
    }

    public function workerRemoveAction($orgId, $id)
    {
        $em = $this->getDoctrine()->getEntityManager();
        $worker = $em->getRepository('OrgsBundle:Worker')->findOneBy(array('id' => $id));

        $em->remove($worker);
        $em->flush();

        $this->addFlash(
            'notice',
            $this->get('translator')->trans('notice.removing.worker.successful',
                array('%fullname%' => $worker->getFullName())));

        return $this->redirect($this->generateUrl('orgs_info_organization', array('id' => $orgId)));
    }

}

src/Organizations/OrgsBundle/Resources/views/Worker/worker_edit.html.twig
{# src/Organizations\OrgsBundle/Resources/views/Worker/worker_new.html.twig #}
{% extends '::base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/orgs/css/orgs.css') }}"/>
{% endblock %}

{% block title %}{% trans with {'%fullname%': worker.fullName } %}editing.worker.fullname{% endtrans %}{% endblock %}

{% block body %}

    <p class="title_operation">{% trans with {'%fullname%': worker.fullName } %}editing.worker.fullname{% endtrans %}</p>
    <div class="form_view">
        <form action="{{path('worker_edit', {'orgId': orgId, 'id': worker.id })}}" method="post" {{ form_enctype(form) }}>

            {% include 'OrgsBundle:Worker:worker_form_fields.html.twig' %}

        </form>

        <p>
            <a href="{{ path('worker_info', {'orgId': orgId, 'id': worker.id }) }}">{% trans %}to.the.info.about.worker{% endtrans %}</a>
        </p>

    </div>
{% endblock %}

src/Organizations/OrgsBundle/Resources/views/Worker/worker_form_fields.html.twig
{# src/Organizations\OrgsBundle/Resources/views/Worker/worker_form_fields.html.twig #}
            <div class="table_error_form">
                {{ form_errors(form) }}
            </div>

            <table class="table_form">
                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.lastname, 'worker.secondname') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.lastname)}}
                        </div>
                        {{form_widget(form.lastname)}}
                    </td>
                </tr>

                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.firstname, 'worker.firstname') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.firstname)}}
                        </div>
                        {{form_widget(form.firstname)}}
                    </td>
                </tr>
                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.middlename, 'worker.middlename') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.middlename)}}
                        </div>
                        {{form_widget(form.middlename)}}
                    </td>
                </tr>
                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.birthday, 'worker.birthday') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.birthday)}}
                        </div>
                        {{form_widget(form.birthday)}}
                    </td>
                </tr>
                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.inn, 'worker.inn') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.inn)}}
                        </div>
                        {{form_widget(form.inn)}}
                    </td>
                </tr>
                <tr>
                    <td class="table_label_form">
                        <div>
                            {{ form_label(form.snils, 'worker.snils') }}
                        </div>
                    </td>
                    <td class="table_field_form">
                        <div class="table_error_form">
                            {{form_errors(form.snils)}}
                        </div>
                        {{form_widget(form.snils)}}
                    </td>
                </tr>

                <tr>
                    <td class="table_label_form">
                    </td>
                    <td class="table_field_form">
                        {{ form_rest(form) }}
                    </td>
                </tr>

                <tr>
                    <td class="table_label_form">
                    </td>
                    <td class="table_submit_form">
                        <div>
                            <input type="submit"/>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </div>
                    </td>
                </tr>

            </table>

src/Organizations/OrgsBundle/Resources/views/Worker/worker_info.html.twig
{# src/Organizations\OrgsBundle/Resources/views/Worker/worker_info.html.twig #}
{% extends '::base.html.twig' %}

{% block title %}{% trans with {'%fullname%': worker.fullName } %}info.about.worker.fullname{% endtrans %}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/orgs/css/orgs.css') }}"/>
{% endblock %}

{% block body %}
    <p>
        {% for message in app.session.flashBag.get('notice') %}
            <div class="flash-notice">
                {{ message }}
            </div>
        {% endfor %}
    </p>

    <br /><br /><br />
    <div class="organizations">
        <table>
            <caption>{% trans with {'%fullname%': worker.fullName } %}info.about.worker.fullname{% endtrans %}</caption>
            <tr>
                <td><b>{% trans %}internal.id{% endtrans %}</b></td>
                <td>{{ worker.id }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.secondname{% endtrans %}</b></td>
                <td>{{ worker.lastname }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.firstname{% endtrans %}</b></td>
                <td>{{ worker.firstname }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.middlename{% endtrans %}</b></td>
                <td>{{ worker.middlename }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.birthday{% endtrans %}</b></td>
                <td>
                    {% if worker.birthday is not empty %}
                        {{ worker.birthday|date("d/m/Y") }}
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.inn{% endtrans %}</b></td>
                <td>{{ worker.inn }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}worker.snils{% endtrans %}</b></td>
                <td>{{ worker.snils }}</td>
            </tr>
            <tr>
                <td><b>{% trans %}actions{% endtrans %}</b></td>
                <td>
                    <a href="{{ path('worker_edit', {'orgId': orgId, 'id': worker.id}) }}">{% trans %}action.edit{% endtrans %}</a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="{{ path('worker_remove', {'orgId': orgId, 'id': worker.id}) }}" onclick="javascript:return confirm('{% trans with {'%fullname%': worker.fullname } %}action.remove.worker.question{% endtrans %}')">{% trans %}action.remove{% endtrans %}</a>
                </td>
            </tr>
        </table>

    </div>

    <p>
        <a href="{{ path('orgs_info_organization', {'id': orgId}) }}">{% trans %}to.the.info.about.organization{% endtrans %}</a>
    </p>
{% endblock %}

src/Organizations/OrgsBundle/Resources/views/Worker/worker_new.html.twig
{# src/Organizations\OrgsBundle/Resources/views/Worker/worker_new.html.twig #}
{% extends '::base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('bundles/orgs/css/orgs.css') }}"/>
{% endblock %}

{% block title %}{% trans %}adding.worker.title{% endtrans %}{% endblock %}

{% block body %}

    <p class="title_operation">{% trans %}adding.worker.title{% endtrans %}</p>
    <div class="form_view">
        <form action="{{path('worker_create', {'orgId': orgId})}}" method="post" {{ form_enctype(form) }}>

            {% include 'OrgsBundle:Worker:worker_form_fields.html.twig' %}

        </form>

        <p>
            <a href="{{ path('orgs_info_organization', {'id': orgId}) }}">{% trans %}to.the.info.about.organization{% endtrans %}</a>
        </p>
</div>
{% endblock %}

src/Organizations/OrgsBundle/Resources/views/Worker/workers_list.html.twig
{# src/Organizations\OrgsBundle/Resources/views/Worker/workers_list.html.twig #}
<br /><br /><br />
<div class="organizations">
    <table>
        <caption>{% trans %}list.workers.title{% endtrans %}</caption>
        <tr>
            <th>{% trans %}worker.fullname{% endtrans %}</th>
            <th>{% trans %}worker.inn{% endtrans %}</th>
            <th>{% trans %}worker.snils{% endtrans %}</th>
        </tr>
        {% for key, worker in organization.workers %}
            <tr class="{{cycle(['odd','even'], key)}}">
                <td>
                    <a href="{{ path('worker_info', {'orgId': organization.id, 'id': worker.id}) }}">
                        {{ worker.fullName }}
                    </a>
                </td>
                <td>
                    {{ worker.inn }}
                </td>
                <td>
                    {{ worker.snils }}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>